name: Generate Daily Markdown

on:
  schedule:
    # This is an automatic trigger that runs daily at 7:01 UTC (15:01 Beijing Time)
    # The cron syntax is: minute hour day_of_month month day_of_week
    - cron: '01 7 * * *'  # Runs daily at 7:01 UTC
  
  # This allows the workflow to be manually triggered from GitHub UI
  # You can run it anytime by clicking "Run workflow" button on the Actions tab
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-wordpress-xmlrpc
        pip list  # Display installed packages and versions

    - name: Generate Markdown
      env:
        PRODUCTHUNT_DEVELOPER_TOKEN: ${{ secrets.PRODUCTHUNT_DEVELOPER_TOKEN }}
      run: |
        python scripts/product_hunt_list_to_md.py

    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Generated daily content" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push --force https://${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/producthunt-daily-hot.git HEAD:main
